Exercicio-5
samuelcamilodacosta/Helpper-Origins pull request #2
Opened 2021-11-08 21:28 UTC by samuelcamilodacosta

2021-11-08 22:16 UTC, alanrocha-helpper requested changes

2021-11-08 22:16 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +button.addEventListener('click', function (e: MouseEvent) {
Nome da variavel `e`

2021-11-08 22:16 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +import Words from "./class.js";
importar do class.ts

2021-11-08 23:20 UTC, samuelcamilodacosta commented on Sprint-2/Exercicio-5/script.ts
> +import Words from "./class.js";
"Um caminho de importação não pode terminar com uma extensão '.ts'. Considere importar './class.js'.ts(2691)"
toda vez que tento importar o class.ts ele apresenta esse erro, ele só funciona se eu importar class ou class.js

2021-11-08 23:40 UTC, samuelcamilodacosta commented on Sprint-2/Exercicio-5/class.ts
> +        let vowels = ['a', 'e', 'i', 'o', 'u'];
feito.

2021-11-08 23:41 UTC, samuelcamilodacosta commented on Sprint-2/Exercicio-5/class.ts
> +        //this.word = this.word.normalize('NFD');
código comentado removido

2021-11-08 23:41 UTC, samuelcamilodacosta commented on Sprint-2/Exercicio-5/script.ts
> +button.addEventListener('click', function (e: MouseEvent) {
alterado o nome para event

2021-11-09 21:25 UTC, alanrocha-helpper requested changes

2021-11-09 21:25 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/class.ts
> +        this._vowels = ['a', 'e', 'i', 'o', 'u']
Esse cara aqui como é um valor fixo, já pode ser preenchido na declaração, não precisa ser no construtor

2021-11-09 21:25 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/class.ts
> +        let result: string[] = this._word.toLowerCase().normalize('NFD').split('').filter((letter: string) => this._vowels.includes(letter));
Gostei disso aqui.

2021-11-09 21:25 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +import Words from "./class.js";
Desculpa cara, você não vai importar do `./class.ts` , como ambos são jtypescript você importa como `./class`

2021-11-10 18:58 UTC, samuelcamilodacosta commented
Adicionei comentários ao código tentando seguir o padrão TSDoc.
Acrescentei também uma interface visível para o usuário a questão (a).
Adicionei todas as alterações pedidas nos reviews, verificar alterações por favor.

2021-11-10 22:20 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/class.ts
> +        /**
o comentário de documentação vem fora da função, antes da sua declaração.

2021-11-10 22:21 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/class.ts
> +        * @parameter this._word - the sentence received by the constructor for the variable word
Essa função não tem parametro, visto que a palavra é passada para a classe na sua instanciação, via construtor

2021-11-10 22:28 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +/**
comentários desse tipos em blocos servem para documentar funções. no caso desse código, que é um script, pode-se documentar utilizando `// comentário explicativo ` antes do que se quer documentar

2021-11-10 22:29 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +button.addEventListener('click', function (event: MouseEvent) {
para que você possa utilizar um comentário em bloco para documentar um função aqui, sugiro que você extraia a função passada para o `addEventListener` e passe a função onde é esperada `addEventListener('click', suaFuncao)`

2021-11-10 22:30 UTC, alanrocha-helpper requested changes
ALguns apontamentos feitos sobre a utilização dos comentários

2021-11-10 22:58 UTC, alanrocha-helpper requested changes
Apontamentos realizados nos arquivos

2021-11-11 22:24 UTC, alanrocha-helpper approved these changes

2021-11-11 22:24 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/script.ts
> +
não deixar espaço aqui

2021-11-11 22:24 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-5/class.ts
> +    /**
deixar uma linha de espaço antes do comentário

2021-11-12 01:56 UTC, pedro-monteiro-helpper approved these changes

2021-11-12 01:57 UTC, merged