Exercicio-7 imperativo e funcional
samuelcamilodacosta/Helpper-Origins pull request #6
Opened 2021-11-08 22:56 UTC by samuelcamilodacosta

2021-11-10 23:25 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-1/class.ts
> +export default class List {
Adicionar comentário de documentação seguindo o padrão TSDoc

2021-11-10 23:25 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-1/class.ts
> +         */
Adicionar comentário de documentação seguindo o padrão TSDoc

esse método pode ser privado, visto que será utilizado somente dentro da própria classe

2021-11-10 23:27 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-1/class.ts
> +         */
Adicionar comentário de documentação seguindo o padrão TSDoc


Tipar o retorno da função

2021-11-10 23:30 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-1/class.ts
> +            if(parseFloat(this._list[index]) || this._list[index] == "0") continue;
Mudar a condição para que você tenha somete o bloco onde você seta o validation e usa o break;

Ter um bloco de if somente para escrever continue não é uma boa pratica, e dificulta o entendimento do código

2021-11-10 23:32 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-1/script.ts
> +import List from "./class.js";
Adicionar comentários

2021-11-10 23:33 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +         * The smallerValue compares if the value is smaller than it, if it is,
Adicionar comentário de documentação seguindo o padrão TSDoc

2021-11-10 23:34 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +         * by the number of elements in the list, obtaining the average value.
não deixar código não utilizado ou trecho de código comentando no meio do código. se não vai ser utilizado, remover

2021-11-10 23:34 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +         * it will become the value.
Se não for utilizar a variavel index, não precisa passa-la como parametro da função 
 basta um `(arrayItem) => `

2021-11-10 23:35 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +         */
Adicionar comentário de documentação seguindo o padrão TSDoc

tipar o retorno da função

2021-11-10 23:35 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +export default class List {
Adicionar comentário padrão TSDoc

2021-11-10 23:36 UTC, alanrocha-helpper requested changes
Comentários adicionados aos arquivos referentes

2021-11-12 16:32 UTC, samuelcamilodacosta commented
Alterações realizadas

2021-11-13 14:08 UTC, alanrocha-helpper requested changes

2021-11-13 14:08 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +    findBiggerSmallerAndAverageValue(){
tipar o retorno da função

2021-11-13 14:08 UTC, alanrocha-helpper commented on Sprint-2/Exercicio-7-Resposta-2/class.ts
> +    numericalList(){
tipar o retorno da função

2021-11-13 18:02 UTC, samuelcamilodacosta commented
Alterações realizadas. Não sei por qual motivos, mas as alterações que foram pedidas aqui não se misturaram com as antigas como ocorreu no exercício 6 :S

2022-01-09 03:13 UTC, merged